//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceExamples.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:thesecretserver.com", ConfigurationName="ServiceReference.SSWebServiceSoap")]
    public interface SSWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.AuthenticateResult Authenticate(string username, string password, string organization, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/AuthenticateRADIUS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.AuthenticateResult AuthenticateRADIUS(string username, string password, string organization, string domain, string radiusPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetTokenIsValid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.TokenIsValidResult GetTokenIsValid(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetSecret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetSecretResult GetSecret(string token, int secretId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetCheckOutStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetCheckOutStatusResult GetCheckOutStatus(string token, int secretId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult ChangePassword(string token, string currentPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/SearchWebPasswordsForUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetWebPasswordResult SearchWebPasswordsForUrl(string token, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/SearchSecrets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.SearchSecretsResult SearchSecrets(string token, string searchTerm);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetFavorites", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetFavoritesResult GetFavorites(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/UpdateIsFavorite", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult UpdateIsFavorite(string token, int secretId, bool isFavorite);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/AddSecret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.AddSecretResult AddSecret(string token, int secretTypeId, string secretName, int[] secretFieldIds, string[] secretItemValues, int folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetSecretTemplateFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetSecretTemplateFieldsResult GetSecretTemplateFields(string token, int secretTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/UpdateSecret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult UpdateSecret(string token, WebServiceExamples.ServiceReference.Secret secret);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetSecretTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetSecretTemplatesResult GetSecretTemplates(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GeneratePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GeneratePasswordResult GeneratePassword(string token, int secretFieldId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/DeactivateSecret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult DeactivateSecret(string token, int secretId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/VersionGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.VersionGetResult VersionGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/FolderGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetFolderResult FolderGet(string token, int folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/FolderUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult FolderUpdate(string token, WebServiceExamples.ServiceReference.Folder modifiedFolder);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/FolderGetAllChildren", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetFoldersResult FolderGetAllChildren(string token, int parentFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/FolderCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.CreateFolderResult FolderCreate(string token, string folderName, int parentFolderId, int folderTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/SearchFolders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.SearchFolderResult SearchFolders(string token, string folderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/DownloadFileAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.FileDownloadResult DownloadFileAttachment(string token, int secretId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/DownloadFileAttachmentByItemId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.FileDownloadResult DownloadFileAttachmentByItemId(string token, int secretId, int secretItemId);
        
        // CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/UploadFileAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.UploadFileAttachmentResponse UploadFileAttachment(WebServiceExamples.ServiceReference.UploadFileAttachmentRequest request);
        
        // CODEGEN: Parameter 'fileData' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/UploadFileAttachmentByItemId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdResponse UploadFileAttachmentByItemId(WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/ExpireSecret", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult ExpireSecret(string token, int secretId);
        
        // CODEGEN: Parameter 'checkOutInterval' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/SetCheckOutEnabled", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.SetCheckOutEnabledResponse SetCheckOutEnabled(WebServiceExamples.ServiceReference.SetCheckOutEnabledRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/ImportXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.WebServiceResult ImportXML(string token, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:thesecretserver.com/GetSecretAudit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceExamples.ServiceReference.GetSecretAuditResult GetSecretAudit(string token, int secretId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class AuthenticateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class AuditSecret : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int auditSecretIdField;
        
        private int secretIdField;
        
        private System.DateTime dateRecordedField;
        
        private string actionField;
        
        private string notesField;
        
        private int userIdField;
        
        private string secretNameField;
        
        private string ipAddressField;
        
        private int referenceIdField;
        
        private string byUserDisplayNameField;
        
        private string ticketNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AuditSecretId {
            get {
                return this.auditSecretIdField;
            }
            set {
                this.auditSecretIdField = value;
                this.RaisePropertyChanged("AuditSecretId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SecretId {
            get {
                return this.secretIdField;
            }
            set {
                this.secretIdField = value;
                this.RaisePropertyChanged("SecretId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateRecorded {
            get {
                return this.dateRecordedField;
            }
            set {
                this.dateRecordedField = value;
                this.RaisePropertyChanged("DateRecorded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SecretName {
            get {
                return this.secretNameField;
            }
            set {
                this.secretNameField = value;
                this.RaisePropertyChanged("SecretName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("IpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ReferenceId {
            get {
                return this.referenceIdField;
            }
            set {
                this.referenceIdField = value;
                this.RaisePropertyChanged("ReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ByUserDisplayName {
            get {
                return this.byUserDisplayNameField;
            }
            set {
                this.byUserDisplayNameField = value;
                this.RaisePropertyChanged("ByUserDisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TicketNumber {
            get {
                return this.ticketNumberField;
            }
            set {
                this.ticketNumberField = value;
                this.RaisePropertyChanged("TicketNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetSecretAuditResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private AuditSecret[] secretAuditsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public AuditSecret[] SecretAudits {
            get {
                return this.secretAuditsField;
            }
            set {
                this.secretAuditsField = value;
                this.RaisePropertyChanged("SecretAudits");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class SearchFolderResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private Folder[] foldersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Folder[] Folders {
            get {
                return this.foldersField;
            }
            set {
                this.foldersField = value;
                this.RaisePropertyChanged("Folders");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class Folder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private int typeIdField;
        
        private int parentFolderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
                this.RaisePropertyChanged("TypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ParentFolderId {
            get {
                return this.parentFolderIdField;
            }
            set {
                this.parentFolderIdField = value;
                this.RaisePropertyChanged("ParentFolderId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetFoldersResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Folder[] foldersField;
        
        private string[] errorsField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Folder[] Folders {
            get {
                return this.foldersField;
            }
            set {
                this.foldersField = value;
                this.RaisePropertyChanged("Folders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetFolderResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Folder folderField;
        
        private string[] errorsField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Folder Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
                this.RaisePropertyChanged("Folder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class VersionGetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GeneratePasswordResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string generatedPasswordField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GeneratedPassword {
            get {
                return this.generatedPasswordField;
            }
            set {
                this.generatedPasswordField = value;
                this.RaisePropertyChanged("GeneratedPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class SecretTemplate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private SecretField[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public SecretField[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class SecretField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string displayNameField;
        
        private int idField;
        
        private bool isPasswordField;
        
        private bool isUrlField;
        
        private bool isNotesField;
        
        private bool isFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
                this.RaisePropertyChanged("DisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsPassword {
            get {
                return this.isPasswordField;
            }
            set {
                this.isPasswordField = value;
                this.RaisePropertyChanged("IsPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsUrl {
            get {
                return this.isUrlField;
            }
            set {
                this.isUrlField = value;
                this.RaisePropertyChanged("IsUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsNotes {
            get {
                return this.isNotesField;
            }
            set {
                this.isNotesField = value;
                this.RaisePropertyChanged("IsNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsFile {
            get {
                return this.isFileField;
            }
            set {
                this.isFileField = value;
                this.RaisePropertyChanged("IsFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetSecretTemplatesResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private SecretTemplate[] secretTemplatesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SecretTemplate[] SecretTemplates {
            get {
                return this.secretTemplatesField;
            }
            set {
                this.secretTemplatesField = value;
                this.RaisePropertyChanged("SecretTemplates");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetSecretTemplateFieldsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private SecretField[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SecretField[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class AddSecretResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private Secret secretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Secret Secret {
            get {
                return this.secretField;
            }
            set {
                this.secretField = value;
                this.RaisePropertyChanged("Secret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class Secret : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private SecretItem[] itemsField;
        
        private int idField;
        
        private int secretTypeIdField;
        
        private int folderIdField;
        
        private bool isWebLauncherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SecretItem[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SecretTypeId {
            get {
                return this.secretTypeIdField;
            }
            set {
                this.secretTypeIdField = value;
                this.RaisePropertyChanged("SecretTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
                this.RaisePropertyChanged("FolderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsWebLauncher {
            get {
                return this.isWebLauncherField;
            }
            set {
                this.isWebLauncherField = value;
                this.RaisePropertyChanged("IsWebLauncher");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class SecretItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private System.Nullable<int> idField;
        
        private System.Nullable<int> fieldIdField;
        
        private string fieldNameField;
        
        private bool isFileField;
        
        private bool isNotesField;
        
        private bool isPasswordField;
        
        private string fieldDisplayNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> FieldId {
            get {
                return this.fieldIdField;
            }
            set {
                this.fieldIdField = value;
                this.RaisePropertyChanged("FieldId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsFile {
            get {
                return this.isFileField;
            }
            set {
                this.isFileField = value;
                this.RaisePropertyChanged("IsFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsNotes {
            get {
                return this.isNotesField;
            }
            set {
                this.isNotesField = value;
                this.RaisePropertyChanged("IsNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsPassword {
            get {
                return this.isPasswordField;
            }
            set {
                this.isPasswordField = value;
                this.RaisePropertyChanged("IsPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FieldDisplayName {
            get {
                return this.fieldDisplayNameField;
            }
            set {
                this.fieldDisplayNameField = value;
                this.RaisePropertyChanged("FieldDisplayName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetFavoritesResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private SecretSummary[] secretSummariesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SecretSummary[] SecretSummaries {
            get {
                return this.secretSummariesField;
            }
            set {
                this.secretSummariesField = value;
                this.RaisePropertyChanged("SecretSummaries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class SecretSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int secretIdField;
        
        private string secretNameField;
        
        private string secretTypeNameField;
        
        private int secretTypeIdField;
        
        private int folderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SecretId {
            get {
                return this.secretIdField;
            }
            set {
                this.secretIdField = value;
                this.RaisePropertyChanged("SecretId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SecretName {
            get {
                return this.secretNameField;
            }
            set {
                this.secretNameField = value;
                this.RaisePropertyChanged("SecretName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecretTypeName {
            get {
                return this.secretTypeNameField;
            }
            set {
                this.secretTypeNameField = value;
                this.RaisePropertyChanged("SecretTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SecretTypeId {
            get {
                return this.secretTypeIdField;
            }
            set {
                this.secretTypeIdField = value;
                this.RaisePropertyChanged("SecretTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
                this.RaisePropertyChanged("FolderId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class SearchSecretsResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private SecretSummary[] secretSummariesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SecretSummary[] SecretSummaries {
            get {
                return this.secretSummariesField;
            }
            set {
                this.secretSummariesField = value;
                this.RaisePropertyChanged("SecretSummaries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class WebPassword : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string secretNameField;
        
        private string urlField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SecretName {
            get {
                return this.secretNameField;
            }
            set {
                this.secretNameField = value;
                this.RaisePropertyChanged("SecretName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetWebPasswordResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private WebPassword[] webPasswordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public WebPassword[] WebPasswords {
            get {
                return this.webPasswordsField;
            }
            set {
                this.webPasswordsField = value;
                this.RaisePropertyChanged("WebPasswords");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileDownloadResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateFolderResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class WebServiceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class FileDownloadResult : WebServiceResult {
        
        private byte[] fileAttachmentField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] FileAttachment {
            get {
                return this.fileAttachmentField;
            }
            set {
                this.fileAttachmentField = value;
                this.RaisePropertyChanged("FileAttachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class CreateFolderResult : WebServiceResult {
        
        private int folderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FolderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
                this.RaisePropertyChanged("FolderId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetCheckOutStatusResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private Secret secretField;
        
        private int checkOutMinutesRemainingField;
        
        private bool isCheckedOutField;
        
        private string checkOutUserDisplayNameField;
        
        private int checkOutUserIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Secret Secret {
            get {
                return this.secretField;
            }
            set {
                this.secretField = value;
                this.RaisePropertyChanged("Secret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CheckOutMinutesRemaining {
            get {
                return this.checkOutMinutesRemainingField;
            }
            set {
                this.checkOutMinutesRemainingField = value;
                this.RaisePropertyChanged("CheckOutMinutesRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsCheckedOut {
            get {
                return this.isCheckedOutField;
            }
            set {
                this.isCheckedOutField = value;
                this.RaisePropertyChanged("IsCheckedOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CheckOutUserDisplayName {
            get {
                return this.checkOutUserDisplayNameField;
            }
            set {
                this.checkOutUserDisplayNameField = value;
                this.RaisePropertyChanged("CheckOutUserDisplayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CheckOutUserId {
            get {
                return this.checkOutUserIdField;
            }
            set {
                this.checkOutUserIdField = value;
                this.RaisePropertyChanged("CheckOutUserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class GetSecretResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private Secret secretField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Secret Secret {
            get {
                return this.secretField;
            }
            set {
                this.secretField = value;
                this.RaisePropertyChanged("Secret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:thesecretserver.com")]
    public partial class TokenIsValidResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private int maxOfflineSecondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MaxOfflineSeconds {
            get {
                return this.maxOfflineSecondsField;
            }
            set {
                this.maxOfflineSecondsField = value;
                this.RaisePropertyChanged("MaxOfflineSeconds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileAttachment", WrapperNamespace="urn:thesecretserver.com", IsWrapped=true)]
    public partial class UploadFileAttachmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=1)]
        public int secretId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=3)]
        public string fileName;
        
        public UploadFileAttachmentRequest() {
        }
        
        public UploadFileAttachmentRequest(string token, int secretId, byte[] fileData, string fileName) {
            this.token = token;
            this.secretId = secretId;
            this.fileData = fileData;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileAttachmentResponse", WrapperNamespace="urn:thesecretserver.com", IsWrapped=true)]
    public partial class UploadFileAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=0)]
        public WebServiceExamples.ServiceReference.WebServiceResult UploadFileAttachmentResult;
        
        public UploadFileAttachmentResponse() {
        }
        
        public UploadFileAttachmentResponse(WebServiceExamples.ServiceReference.WebServiceResult UploadFileAttachmentResult) {
            this.UploadFileAttachmentResult = UploadFileAttachmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileAttachmentByItemId", WrapperNamespace="urn:thesecretserver.com", IsWrapped=true)]
    public partial class UploadFileAttachmentByItemIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=1)]
        public int secretId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=2)]
        public int secretItemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=4)]
        public string fileName;
        
        public UploadFileAttachmentByItemIdRequest() {
        }
        
        public UploadFileAttachmentByItemIdRequest(string token, int secretId, int secretItemId, byte[] fileData, string fileName) {
            this.token = token;
            this.secretId = secretId;
            this.secretItemId = secretItemId;
            this.fileData = fileData;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileAttachmentByItemIdResponse", WrapperNamespace="urn:thesecretserver.com", IsWrapped=true)]
    public partial class UploadFileAttachmentByItemIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=0)]
        public WebServiceExamples.ServiceReference.WebServiceResult UploadFileAttachmentByItemIdResult;
        
        public UploadFileAttachmentByItemIdResponse() {
        }
        
        public UploadFileAttachmentByItemIdResponse(WebServiceExamples.ServiceReference.WebServiceResult UploadFileAttachmentByItemIdResult) {
            this.UploadFileAttachmentByItemIdResult = UploadFileAttachmentByItemIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCheckOutEnabled", WrapperNamespace="urn:thesecretserver.com", IsWrapped=true)]
    public partial class SetCheckOutEnabledRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=0)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=1)]
        public int secretId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=2)]
        public bool setCheckOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=3)]
        public bool setPasswordChangeOnCheckIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> checkOutInterval;
        
        public SetCheckOutEnabledRequest() {
        }
        
        public SetCheckOutEnabledRequest(string token, int secretId, bool setCheckOut, bool setPasswordChangeOnCheckIn, System.Nullable<int> checkOutInterval) {
            this.token = token;
            this.secretId = secretId;
            this.setCheckOut = setCheckOut;
            this.setPasswordChangeOnCheckIn = setPasswordChangeOnCheckIn;
            this.checkOutInterval = checkOutInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCheckOutEnabledResponse", WrapperNamespace="urn:thesecretserver.com", IsWrapped=true)]
    public partial class SetCheckOutEnabledResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:thesecretserver.com", Order=0)]
        public WebServiceExamples.ServiceReference.WebServiceResult SetCheckOutEnabledResult;
        
        public SetCheckOutEnabledResponse() {
        }
        
        public SetCheckOutEnabledResponse(WebServiceExamples.ServiceReference.WebServiceResult SetCheckOutEnabledResult) {
            this.SetCheckOutEnabledResult = SetCheckOutEnabledResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SSWebServiceSoapChannel : WebServiceExamples.ServiceReference.SSWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SSWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceExamples.ServiceReference.SSWebServiceSoap>, WebServiceExamples.ServiceReference.SSWebServiceSoap {
        
        public SSWebServiceSoapClient() {
        }
        
        public SSWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebServiceExamples.ServiceReference.AuthenticateResult Authenticate(string username, string password, string organization, string domain) {
            return base.Channel.Authenticate(username, password, organization, domain);
        }
        
        public WebServiceExamples.ServiceReference.AuthenticateResult AuthenticateRADIUS(string username, string password, string organization, string domain, string radiusPassword) {
            return base.Channel.AuthenticateRADIUS(username, password, organization, domain, radiusPassword);
        }
        
        public WebServiceExamples.ServiceReference.TokenIsValidResult GetTokenIsValid(string token) {
            return base.Channel.GetTokenIsValid(token);
        }
        
        public WebServiceExamples.ServiceReference.GetSecretResult GetSecret(string token, int secretId) {
            return base.Channel.GetSecret(token, secretId);
        }
        
        public WebServiceExamples.ServiceReference.GetCheckOutStatusResult GetCheckOutStatus(string token, int secretId) {
            return base.Channel.GetCheckOutStatus(token, secretId);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult ChangePassword(string token, string currentPassword, string newPassword) {
            return base.Channel.ChangePassword(token, currentPassword, newPassword);
        }
        
        public WebServiceExamples.ServiceReference.GetWebPasswordResult SearchWebPasswordsForUrl(string token, string url) {
            return base.Channel.SearchWebPasswordsForUrl(token, url);
        }
        
        public WebServiceExamples.ServiceReference.SearchSecretsResult SearchSecrets(string token, string searchTerm) {
            return base.Channel.SearchSecrets(token, searchTerm);
        }
        
        public WebServiceExamples.ServiceReference.GetFavoritesResult GetFavorites(string token) {
            return base.Channel.GetFavorites(token);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult UpdateIsFavorite(string token, int secretId, bool isFavorite) {
            return base.Channel.UpdateIsFavorite(token, secretId, isFavorite);
        }
        
        public WebServiceExamples.ServiceReference.AddSecretResult AddSecret(string token, int secretTypeId, string secretName, int[] secretFieldIds, string[] secretItemValues, int folderId) {
            return base.Channel.AddSecret(token, secretTypeId, secretName, secretFieldIds, secretItemValues, folderId);
        }
        
        public WebServiceExamples.ServiceReference.GetSecretTemplateFieldsResult GetSecretTemplateFields(string token, int secretTypeId) {
            return base.Channel.GetSecretTemplateFields(token, secretTypeId);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult UpdateSecret(string token, WebServiceExamples.ServiceReference.Secret secret) {
            return base.Channel.UpdateSecret(token, secret);
        }
        
        public WebServiceExamples.ServiceReference.GetSecretTemplatesResult GetSecretTemplates(string token) {
            return base.Channel.GetSecretTemplates(token);
        }
        
        public WebServiceExamples.ServiceReference.GeneratePasswordResult GeneratePassword(string token, int secretFieldId) {
            return base.Channel.GeneratePassword(token, secretFieldId);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult DeactivateSecret(string token, int secretId) {
            return base.Channel.DeactivateSecret(token, secretId);
        }
        
        public WebServiceExamples.ServiceReference.VersionGetResult VersionGet() {
            return base.Channel.VersionGet();
        }
        
        public WebServiceExamples.ServiceReference.GetFolderResult FolderGet(string token, int folderId) {
            return base.Channel.FolderGet(token, folderId);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult FolderUpdate(string token, WebServiceExamples.ServiceReference.Folder modifiedFolder) {
            return base.Channel.FolderUpdate(token, modifiedFolder);
        }
        
        public WebServiceExamples.ServiceReference.GetFoldersResult FolderGetAllChildren(string token, int parentFolderId) {
            return base.Channel.FolderGetAllChildren(token, parentFolderId);
        }
        
        public WebServiceExamples.ServiceReference.CreateFolderResult FolderCreate(string token, string folderName, int parentFolderId, int folderTypeId) {
            return base.Channel.FolderCreate(token, folderName, parentFolderId, folderTypeId);
        }
        
        public WebServiceExamples.ServiceReference.SearchFolderResult SearchFolders(string token, string folderName) {
            return base.Channel.SearchFolders(token, folderName);
        }
        
        public WebServiceExamples.ServiceReference.FileDownloadResult DownloadFileAttachment(string token, int secretId) {
            return base.Channel.DownloadFileAttachment(token, secretId);
        }
        
        public WebServiceExamples.ServiceReference.FileDownloadResult DownloadFileAttachmentByItemId(string token, int secretId, int secretItemId) {
            return base.Channel.DownloadFileAttachmentByItemId(token, secretId, secretItemId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceExamples.ServiceReference.UploadFileAttachmentResponse WebServiceExamples.ServiceReference.SSWebServiceSoap.UploadFileAttachment(WebServiceExamples.ServiceReference.UploadFileAttachmentRequest request) {
            return base.Channel.UploadFileAttachment(request);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult UploadFileAttachment(string token, int secretId, byte[] fileData, string fileName) {
            WebServiceExamples.ServiceReference.UploadFileAttachmentRequest inValue = new WebServiceExamples.ServiceReference.UploadFileAttachmentRequest();
            inValue.token = token;
            inValue.secretId = secretId;
            inValue.fileData = fileData;
            inValue.fileName = fileName;
            WebServiceExamples.ServiceReference.UploadFileAttachmentResponse retVal = ((WebServiceExamples.ServiceReference.SSWebServiceSoap)(this)).UploadFileAttachment(inValue);
            return retVal.UploadFileAttachmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdResponse WebServiceExamples.ServiceReference.SSWebServiceSoap.UploadFileAttachmentByItemId(WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdRequest request) {
            return base.Channel.UploadFileAttachmentByItemId(request);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult UploadFileAttachmentByItemId(string token, int secretId, int secretItemId, byte[] fileData, string fileName) {
            WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdRequest inValue = new WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdRequest();
            inValue.token = token;
            inValue.secretId = secretId;
            inValue.secretItemId = secretItemId;
            inValue.fileData = fileData;
            inValue.fileName = fileName;
            WebServiceExamples.ServiceReference.UploadFileAttachmentByItemIdResponse retVal = ((WebServiceExamples.ServiceReference.SSWebServiceSoap)(this)).UploadFileAttachmentByItemId(inValue);
            return retVal.UploadFileAttachmentByItemIdResult;
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult ExpireSecret(string token, int secretId) {
            return base.Channel.ExpireSecret(token, secretId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceExamples.ServiceReference.SetCheckOutEnabledResponse WebServiceExamples.ServiceReference.SSWebServiceSoap.SetCheckOutEnabled(WebServiceExamples.ServiceReference.SetCheckOutEnabledRequest request) {
            return base.Channel.SetCheckOutEnabled(request);
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult SetCheckOutEnabled(string token, int secretId, bool setCheckOut, bool setPasswordChangeOnCheckIn, System.Nullable<int> checkOutInterval) {
            WebServiceExamples.ServiceReference.SetCheckOutEnabledRequest inValue = new WebServiceExamples.ServiceReference.SetCheckOutEnabledRequest();
            inValue.token = token;
            inValue.secretId = secretId;
            inValue.setCheckOut = setCheckOut;
            inValue.setPasswordChangeOnCheckIn = setPasswordChangeOnCheckIn;
            inValue.checkOutInterval = checkOutInterval;
            WebServiceExamples.ServiceReference.SetCheckOutEnabledResponse retVal = ((WebServiceExamples.ServiceReference.SSWebServiceSoap)(this)).SetCheckOutEnabled(inValue);
            return retVal.SetCheckOutEnabledResult;
        }
        
        public WebServiceExamples.ServiceReference.WebServiceResult ImportXML(string token, string xml) {
            return base.Channel.ImportXML(token, xml);
        }
        
        public WebServiceExamples.ServiceReference.GetSecretAuditResult GetSecretAudit(string token, int secretId) {
            return base.Channel.GetSecretAudit(token, secretId);
        }
    }
}
